global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  group_by: ['alertname']
  group_interval: 30s
  repeat_interval: 30s
  group_wait: 30s
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#observability-workshop'
    send_resolved: true
